global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'resource-service:8081'
          - 'song-service:8082'
          - 'resource-processor:8083'
          - 'storage-service:8084'
